#61 [US] - Backend do cadastro de usuário
fga-eps-mds/MDS-2020-2-G6 pull request #108
Opened 2021-03-15 01:05 UTC by Joao-Moura

## Descrição
- Implementação da API de cadastro de usuário, com rotas, serialização, viewsets e models reformulados.

## Está concertando alguma issue aberta?
- #61 

## Tarefas gerais realizadas
- Realização da implementação das rotas de registro de cadastros
    - Produtor `signup/productor/`
    - Consumidor `signup/customer/`
- Correção no model **User** que utiliza o AbstractUser (#86)
- Adição dos viewsets para os models Customer e Productor
- Adição de novos scripts
    - `clear_migrations.sh`: Script para limpeza das migrations do Django.
    - `create_superuser.sh`: Script para criação de super user padrão. 

## Testando a API
### Consumidor
#### Requisição
```json
{
    "user": {
        "username": "exemplo consumidor",
        "email": "consumidor@exemplo.com",
        "password": "123"
    }
}
```

#### Resposta
```json
{
    "user": {
        "username": "exemplo consumidor",
        "email": "consumidor@exemplo.com",
        "password": "123"
    },
    "idPicture": null,
    "idAnun": null
}
```
--------
### Produtor
#### Requisição
```json
{
    "user": {
        "username": "exemplo produtor",
        "email": "produtor@exemplo.com",
        "password": "123"
    }
}
```

#### Resposta
```json
{
    "user": {
        "username": "exemplo produtor",
        "email": "produtor@exemplo.com",
        "password": "123"
    },
    "idPicture": null,
    "idAnun": null
}
```

2021-03-15 21:56 UTC, CarlosFiuza approved these changes
Ok.

2021-03-16 16:05 UTC, VitorLamego reviewed
Primeiramente parabéns pelo PR galera !! Muito bem redigido e explicado !!

2021-03-16 16:08 UTC, VitorLamego requested changes
A única mudança que vejo é na hora de salvar a senha do usuário. Por segurança o correto é criptografar a senha antes de enviá-la para o banco. Uma sugestão é a utilização da biblioteca bcrypt, nunca utilizei com Django, mas fica ai a sugestão para darem uma olhada.

O motivo é para quando acessarmos a rota GET dos usuários não aparecer a sua senha cadastrada e sim um hash daquela senha.

2021-03-16 16:11 UTC, VitorLamego reviewed
E uma sugestão mesmo, pelo que vi do escopo do projeto atual não sei se realmente seria necessário, mas acredito que melhora a nossa organização e possa vir a facilitar algumas manutenções futuras se existir.

Não sei se foi falha minha, mas a rota GET dos usuários está retornando todos os usuários (productors e customers) e talvez para uma melhor organização seria interessante uma rota GET específica para retornar cada grupo de usuário.

2021-03-16 16:34 UTC, Joao-Moura commented
@VitorLamego, em relação ao seu request isso irá ser corrigido (ou melhor ja foi kkkkk) na user story 3 (#81). Isso porque o Django [não armazena raw passwords](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User), e eu não tinha notado isso até iniciar o desenvolvimento da API para login na user story, que estará utilizando uma biblioteca de Tokens chamada [Simple JWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/index.html). 

Para essa biblioteca funcionar ela precisa conferir o username (o email no caso do nosso AbstracUser) e a password. Como nosso banco não estava armazenando as senhas o login nunca encontrava o user, por isso o AbstractUser passou por uma refatoração e o serializer dele também. Então através do método `create_user()` do AbstracUser ele ja irá converter essa raw password para uma hash.

Irei abrir uma branch imediatamente após esse pr passar e quando isso acontecer irei avisar para ja testar.

2021-03-16 16:37 UTC, Joao-Moura commented
Em relação a sua segunda review, a API está utilizando o `List` e `Retrieve` do django-rest. Ou seja a url para acesso de confirmação `signup/confirm` pode ser usada de duas formas:
1. Usando o método **List** e recebendo todo o banco no endpoint `signup/confirm`
2. Utilizando o método **Retrieve** e acessando apenas 1 user do banco no endpoint `signup/confirm/[pk do user que deseja acessar]`

2021-03-16 19:18 UTC, VitorLamego approved these changes
Certo, entendi !! 

Sendo assim acho que tá tudo ok !! Eu vi que tinha a rota pra acessar um usuário específico a partir da pk, mas não tinha visto uma rota que retornasse apenas os productors cadastrados entende ? Mas acredito que isso não afetará o projeto.

2021-03-16 19:19 UTC, merged