Feature/81 login de conta
fga-eps-mds/MDS-2020-2-G6 pull request #112
Opened 2021-03-18 01:53 UTC by Joao-Moura

## Descrição
- Implementação da API para geração de tokens e autenticação

## Está consertando alguma issue aberta?
- #81

## Tarefas gerais realizadas
- Refatorada model do User, agora permitindo [hash passwords](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.password)
- Serializers que utilizavam o User também sofreram pequenas alterações na hora de criação de um User
- Implementação do [Simple JWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/index.html) para tokerização e autenticação de requests
- Adição das rotas:
    - `api/token/` para a geração do token
    - `api/token/refresh/` para refresh de token ja existente

## Pull Requests relacionados

## Testando a API
1. Primeiramente registre um usuário (produtor ou consumidor) no banco de dados (#108)
Obs: Agora, utilizando um registro na nova API, a resposta de um novo registro constará com a senha no formato de hash
```json
{
    "user": {
        "username": "user",
        "email": "user@user.com",
        "password": "pbkdf2_sha256$216000$BONEJlDt0CKw$/dIf0CUqpgNc+eqOWPlTkowqI21vJhw5qS4FyYqbrKQ="
    },
    "idPicture": null,
    "idAnunFav": null,
    "idProdFav": null
}
```

2. Realize uma requisição `POST` no endpoint `api/token/` no seguinte formato `JSON`
```json
{
    "email": "email da conta",
    "password": "senha da conta"
}
```

3. Caso a conta exista no banco, a resposta será `200` seguindo o seguinte formato
```json
{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYxNjg5NDU0MiwianRpIjoiMzQxYmRkN2Q5ZWYyNDVhYThmODRlMTAzOTBlMjJhYmMiLCJ1c2VyX2lkIjoxfQ.lwsrGyWLhhfn4qlvwM8p6YRnz-puptp2oecVQfLeZVU",
    "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE2NDYyNTQyLCJqdGkiOiI1YjI0Nzk3OWMzNWU0MDY3YmUyMzA4NTI2MWU5MzViNCIsInVzZXJfaWQiOjF9.-cce7ItqAaelPeYA8oC5m-gUOyjONH5Z-DKyNPXgZmo"
}
```

4. E caso o email e/ou senha estejam incorretos, uma resposta `401` no seguinte formato será recebida
```json
{
    "detail": "No active account found with the given credentials"
}
```

5. Por fim, se não forem inseridos os campos necessários para a autenticação (email e password), o código `400` será retornado e como resposta o seguinte json
```json
{
    "email": [
        "This field may not be blank."
    ],
    "password": [
        "This field may not be blank."
    ]
}
```

2021-03-18 14:00 UTC, VitorLamego commented
Uma dúvida mesmo, qual a diferenciação entre o token "refresh" e "access" no login ?

2021-03-18 14:03 UTC, VitorLamego requested changes
Pensando na nomenclatura da rota de cadastro "/signup" acredito que a de login poderia ser "/login" ao invés de "/api/token" para seguir um padrão dentro do projeto e acredito que fica mais intuitivo saber o que a rota faz.

2021-03-18 19:01 UTC, Joao-Moura commented
A ideia base por trás do token é gerar pedaços de dados que permitem gerar a autenticação do usuário. O simple JWT e outros tokerizers geram 2 tokens diferentes, os `access tokens` são responsável por permitir a autenticação em si. Já os `refreshs tokens` são responsáveis por conterem dados para a requisição de novos access tokens.

Em relação aos endpoints `api/token/` e `api/token/refresh/` foram trocados para `login/` e `login/refresh/`.

2021-03-18 20:00 UTC, LucasBraunX commented on src/hortum/users/models.py
> +    REQUIRED_FIELDS = ['username']
Password e email não precisam entrar nos REQUIRED_FIELDS também não?

2021-03-18 20:05 UTC, Joao-Moura commented on src/hortum/users/models.py
> +    REQUIRED_FIELDS = ['username']
Não, o email por ele ser `USERNAME_FIELD` o Django já torna ele como required. Agora a password passa por outro processo.

Como a gente ta usando o AbstractUser, ele ja vai possuir alguns atributos pré-definidos e necessários, e um deles é a password. Porém a gente só consegue salvar passwords no formato de `hash`, sendo essa tarefa passada pro serializer das classes que tem o campo OneToOne de User.

Eu expliquei melhor essas carecterísticas nos comentarios desse [pr aqui](https://github.com/fga-eps-mds/2020.2-Hortum/pull/108).

2021-03-18 20:09 UTC, LucasBraunX commented on src/hortum/users/models.py
> +    REQUIRED_FIELDS = ['username']
Entendi. Valeu.

2021-03-18 20:09 UTC, LucasBraunX approved these changes
Testei aqui e funcionou direitinho.

2021-03-21 16:48 UTC, VitorLamego approved these changes
Tudo certo também !! Parabéns galera !!

2021-03-21 17:13 UTC, merged