#138 Melhorando Visão Lógica
fga-eps-mds/MDS-2020-2-G6 pull request #152
Opened 2021-04-04 16:29 UTC by CarlosFiuza

## Descrição
- Revisão e adição de informações na visão lógica do documento de arquitetura.

## Está consertando alguma issue aberta?
- #138 

## Tarefas gerais realizadas
- Adição de informações acerca do funcionamento das requisições web na visão lógica.

2021-04-04 19:59 UTC, brenno-silva requested changes
Acredito que os novos trechos deram uma melhor explicação na utilização do Django Rest, só tem um pequeno erro de digitação.

2021-04-04 19:59 UTC, brenno-silva commented on docs/Documento_de_arquitetura.md
> +<p align = "justify"> &emsp;&emsp; O Django REST já com os dados em mãos, poderá serializar as informações, de maneira mas rápida e fácil que o Django, no formato padrão da API, em JSON. A serializaç
Só um pequeno erro de digitação em "de maneira mas rápida"

2021-04-05 00:50 UTC, CarlosFiuza commented on docs/Documento_de_arquitetura.md
> +<p align = "justify"> &emsp;&emsp; O Django REST já com os dados em mãos, poderá serializar as informações, de maneira mas rápida e fácil que o Django, no formato padrão da API, em JSON. A serializaç
Corrigido

2021-04-05 10:45 UTC, brenno-silva approved these changes

2021-04-05 11:38 UTC, merged