#164 Implemetação de testes que faltavam
fga-eps-mds/MDS-2020-2-G6 pull request #174
Opened 2021-04-13 17:31 UTC by Joao-Moura

## Descrição
- Implentado testes das entidades User, Productor, Customer e Announcements que faltavam

## Está consertando alguma issue aberta?
- #164 

## Tarefas gerais realizadas
- Padronização de testes do Productor e do Customer
- Testes de Announcement adicionados:
    - Deletar anúncio com nome inválido
    - Alterar nome de anúncio para um nome já existente na database
    - Testes de registros de Productor e Customer sem nenhum atributo
    - Registro de customer/productor com email duplicado
    - Testes de tokens válidos e inválidos

## Rodando os testes
1. Abra o docker-compose
2. Rode o seguinte comando
```bash
docker exec 20202-hortum_web_1 bash -c "coverage run manage.py test"
```
3. Veja os testes
```bash
System check identified no issues (0 silenced).
test_create_announcement (hortum.announcement.tests.AnnouncementCreateAPIViewTestCase) ... ok
test_create_announcement_no_authentication (hortum.announcement.tests.AnnouncementCreateAPIViewTestCase) ... ok
test_duplicate_announcement_name (hortum.announcement.tests.AnnouncementCreateAPIViewTestCase) ... ok
test_delete_announcement (hortum.announcement.tests.AnnouncementsDeleteUpdateAPIViewTestCase) ... ok
test_delete_invalid_announcement (hortum.announcement.tests.AnnouncementsDeleteUpdateAPIViewTestCase) ... ok
test_update_multiples_attr_announcement (hortum.announcement.tests.AnnouncementsDeleteUpdateAPIViewTestCase) ... ok
test_update_name_in_database_announcement (hortum.announcement.tests.AnnouncementsDeleteUpdateAPIViewTestCase) ... ok
test_update_one_attr_announcement (hortum.announcement.tests.AnnouncementsDeleteUpdateAPIViewTestCase) ... ok
test_list_all_true_announcement (hortum.announcement.tests.AnnouncementsListAPIViewTestCase) ... ok
test_list_false_inventory_announcement (hortum.announcement.tests.AnnouncementsListAPIViewTestCase) ... ok
test_customer_register (hortum.customer.tests.CustomerRegisterAPIViewTestCase) ... ok
test_duplicate_email_register_customer (hortum.customer.tests.CustomerRegisterAPIViewTestCase) ... ok
test_empty_attr_register_customer (hortum.customer.tests.CustomerRegisterAPIViewTestCase) ... ok
test_duplicate_email_register_productor (hortum.productor.tests.ProductorRegisterAPIViewTestCase) ... ok
test_empty_attr_register_productor (hortum.productor.tests.ProductorRegisterAPIViewTestCase) ... ok
test_productor_register (hortum.productor.tests.ProductorRegisterAPIViewTestCase) ... ok
test_invalid_token_validator (hortum.users.tests.UserTokenObtainAPIViewTestCase) ... ok
test_token_validator (hortum.users.tests.UserTokenObtainAPIViewTestCase) ... ok
test_user_login (hortum.users.tests.UserTokenObtainAPIViewTestCase) ... ok
test_wrong_credentials_login (hortum.users.tests.UserTokenObtainAPIViewTestCase) ... ok

----------------------------------------------------------------------
Ran 20 tests in 4.090s

OK
Destroying test database for alias 'default' ('test_hortum')...
```

2021-04-13 17:45 UTC, matheuscvp approved these changes
Passou no CI e acredito que os problemas não trouxeram nenhum erro

2021-04-13 22:51 UTC, VitorLamego requested changes

2021-04-13 22:51 UTC, VitorLamego commented on src/hortum/users/tests.py
> +        self.assertEqual(response.status_code, 401, msg='Login com credenciais incorretas')
Nessa ocasião a mensagem adequada não seria "Login com credencias corretas" ?? Já que estão testando a ocasião em que é informado as credenciais incorretas

2021-04-13 23:28 UTC, Joao-Moura commented on src/hortum/users/tests.py
> +        self.assertEqual(response.status_code, 401, msg='Login com credenciais incorretas')
Bem notado, irei modificar aqui

2021-04-14 13:59 UTC, VitorLamego approved these changes

2021-04-14 14:01 UTC, merged