#92 Atualizar Dados de Usuário
fga-eps-mds/MDS-2020-2-G6 pull request #178
Opened 2021-04-14 18:42 UTC by brenno-silva

## Descrição
- Criado viewset e serializer no users para edição de dados do usuário

## Está consertando alguma issue aberta?
- #92 

## Tarefas gerais realizadas
- Implementado testes
- Adição do UpdateUserView e UpdateUserSerializer
- Adição do ChangePasswordView e ChangePasswordSerializer

## Como testar
- Rode o comando `docker exec 20202-hortum_web_1 bash -c "coverage run manage.py test && coverage report -m && coverage erase`

2021-04-15 13:29 UTC, LucasBraunX requested changes
Funcionando muito bem, parabéns! Só encontrei um pequeno problema no código.

2021-04-15 13:29 UTC, LucasBraunX commented on src/hortum/users/tests.py
> +        self.creds = {'HTTP_AUTHORIZATION': 'Bearer ' + response.data['access']}
Esses dois atributos tem o mesmo valor, e o auth_token nunca é utilizado. Então seria bom remover ele pra deixar o código mais limpo.

2021-04-15 20:26 UTC, Joao-Moura requested changes
Refiz a viewset de Change password, tornando-a mais enxuta e utilizando os padrões do projeto com mixins. Adicionei também um router customizado para geração das urls.

Bem provável que tenha que refazer os testes também

2021-04-16 12:46 UTC, Joao-Moura requested changes
Massa, vi que vcs conseguiram entender a ideia básica e isso é muito bom, porém o código ainda pode ser simplificado mais ainda. Vou estar solicitando aqui então umas mudanças.

2021-04-16 12:46 UTC, Joao-Moura commented on src/hortum/users/serializer.py
> +                raise serializers.ValidationError('Email ja registrado!')
Em relação à esses if's encadeados. Não há a necessidade de checar se o email que ele está inserindo é o mesmo que o atual já que o `.exists()` já faz isso automaticamente para você.

2021-04-16 12:46 UTC, Joao-Moura commented on src/hortum/users/serializer.py
> +        fields = ['username', 'email']
Não há a necessidade de passar o **username** para essa requisição (pelo menos eu não vi o porque). Sendo assim recomendo retirar (e tirar a linha 35 também).

2021-04-16 12:46 UTC, Joao-Moura commented on src/hortum/users/urls.py
> +router.register(r'update', viewsets.UpdateUserView, basename='updateUser')
Sugiro mudar o nome da rota de update de email para algo mais sugestivo como change-email ou algo do tipo (se fizer isso não esqueça de mudar o basename).

2021-04-16 12:46 UTC, Joao-Moura commented on src/hortum/users/viewsets.py
> +        instance.save()
Não há necessidade de sobrescreve o `update()` já que o mixin faz isso automáticamente, ao contrário do ChangePassword em que é necessário primeiro criptografar a senha para então assim atualizar.

2021-04-16 12:46 UTC, Joao-Moura commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Sugiro mudar o nome de `UpdateUserView` para algo mais sugestivo como `ChangeEmailView`, algo do tipo. Se vc aceitar essa mudança não esqueça de mudar os nomes dos serializers, rotas e testes.

2021-04-16 12:49 UTC, Joao-Moura commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Esqueci de comentar tbm, mais adiciona um comentário falando pra que serve essa viewset que nem eu botei no changePassword

2021-04-16 15:14 UTC, brenno-silva commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Não faria muito sentido mudar o nome já que a classe atualiza o "username" também.

2021-04-16 15:17 UTC, Joao-Moura commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Entendi, então por favor bota um comentário falando sobre isso da viewset kkkkkkkk

2021-04-16 15:24 UTC, CarlosFiuza commented on src/hortum/users/serializer.py
> +                raise serializers.ValidationError('Email ja registrado!')
Tem necessidade sim, pois se o usuário tenta mudar apenas o username o validate vai lançar um ValidationError e vai retornar a response "Email já registrado!"

2021-04-16 15:25 UTC, CarlosFiuza commented on src/hortum/users/serializer.py
> +        fields = ['username', 'email']
Com essa rota é possível atualizar o username também

2021-04-16 15:26 UTC, CarlosFiuza commented on src/hortum/users/urls.py
> +router.register(r'update', viewsets.UpdateUserView, basename='updateUser')
ela faz o update do email e username do User

2021-04-16 15:29 UTC, CarlosFiuza commented on src/hortum/users/viewsets.py
> +        instance.save()
Ok, não há necessidade mesmo.

2021-04-16 15:32 UTC, CarlosFiuza commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Ele também altera o username.

2021-04-16 15:33 UTC, CarlosFiuza commented on src/hortum/users/viewsets.py
> +class UpdateUserView(GenericViewSet, mixins.UpdateModelMixin):
Comentário adicionado

2021-04-16 15:45 UTC, Joao-Moura commented on src/hortum/users/serializer.py
> +                raise serializers.ValidationError('Email ja registrado!')
Mais se vc quer mudar só o username ou só o email é pq o serializer ta errado. Os campos estão como required=True, com isso vc é obrigado a mandar os dois. Alterar pra read_only=True ou só tirar o required acredito que funcione.

2021-04-16 18:49 UTC, CarlosFiuza commented on src/hortum/users/serializer.py
> +                raise serializers.ValidationError('Email ja registrado!')
Corrigido

2021-04-16 19:08 UTC, Joao-Moura approved these changes
Boa, funcionando certinho e com o código django bem curto.

2021-04-17 16:25 UTC, LucasBraunX approved these changes
Funcionando direito

2021-04-17 16:55 UTC, merged