#10 Abertura do Documento de Visão
fga-eps-mds/MDS-2020-2-G6 pull request #18
Opened 2021-02-15 19:44 UTC by brenno-silva

## Descrição
- Abertura do Documento de Visão

## Está concertando alguma issue aberta?
- #10 

## Tipo de mudança
 - [ ] Bugfix
 - [ ] Nova feature
 - [X] Atualização da documentação
 - [ ] Alteração de feature existente

2021-02-15 19:58 UTC, Joao-Moura requested changes
Acredito que seja isso, ficou muito bom a parte das referências.

2021-02-15 19:58 UTC, Joao-Moura commented on mkdocs.yml
> +    - Documento de Visão: "docs/Documento_de_visao.md"
Não é necessário o "docs" na frente dos documentos.

2021-02-15 19:58 UTC, Joao-Moura commented on docs/Documento_de_visao.md
> +|--|--|--|--|--|
Aqui a tabela ta quebrando, acredito que seja só retirar uma coluna.

2021-02-15 19:58 UTC, Joao-Moura commented on docs/Documento_de_visao.md
> +## 1.3. Definições, acrônimos e abreviações
Seria interessante padronizar as definições e abreviações em uma tabela.

2021-02-15 19:59 UTC, Joao-Moura commented on docs/Documento_de_visao.md
> +## 1.3. Definições, acrônimos e abreviações
Eita foram mais linhas do que eu esperava kkkkk, considere apenas a linha 13

2021-02-15 20:08 UTC, Joao-Moura approved these changes
Show de mais

2021-02-17 00:23 UTC, VitorLamego reviewed
Acredito que para abertura de documentação está tudo certo. À medida que a ideia for melhor estruturada a gente vai complementando. Parabéns

2021-02-17 00:24 UTC, VitorLamego approved these changes
Por mim pode fechar a branch.

2021-02-17 00:26 UTC, merged