#181 Alterar ordenação de anúncios na Homepage do comprador
fga-eps-mds/MDS-2020-2-G6 pull request #188
Opened 2021-04-18 19:44 UTC by LucasBraunX

## Descrição
- A ordem da listagem de anúncios foi alterada para mostrar os mais recentes primeiro.

## Está consertando alguma issue aberta?
- #181 

## Tarefas gerais realizadas
- Adição do atributo publicationDate à model de anúncios.
- Definição da forma como a lista de anúncios é ordenada a partir do atributo ordering.
- Adição de teste unitário.

### Como testar:
Crie múltiplos anúncios e então acesse alguma rota que liste anúncios (```/announcement/list```, ```/announcement/list/{nome}``` ou ```/productor/retrieve/{emailb64}```). Os anúncios listados estarão em ordem dos mais recentemente publicados aos mais velhos.

2021-04-19 20:47 UTC, CarlosFiuza requested changes
Muito bom, simples e funcionando. Parabéns

2021-04-19 20:47 UTC, CarlosFiuza commented on src/hortum/announcement/tests.py
> +        self.assertEqual(len(response.data), 2, msg='Falaha na busca por anúncio')
Só uma correção na msg, ta escrito errado.

2021-04-20 23:25 UTC, vital14 approved these changes
Ordenando certinho, parabéns

2021-04-21 01:41 UTC, CarlosFiuza approved these changes
Muito bom trabalho, ordenando direitinho. Parabéns aos envolvidos!

2021-04-21 01:41 UTC, merged