#180 #107 Denunciar usuário
fga-eps-mds/MDS-2020-2-G6 pull request #199
Opened 2021-04-25 07:21 UTC by CarlosFiuza

## Descrição
- Criação de nova entidade Reclamation e seus respectivos viewsets, serializer e tests.
- Modificação do documento de arquitetura para adição de nova entidade

## Está consertando alguma issue aberta?
- #180 
- #107

## Tarefas gerais realizadas
- Criação de nova entidade Reclamation
- Criação de rota `reclamation/create/` para registrar reclamação
- Criação de rota `reclamation/list/{email}` para listar reclamações
- Criação de rota `reclamation/delete/{email}/` para deletar reclamação
- Adição da entidade Reclamation ao documento de arquitetura

### Como testar

#### Registrar reclamação
- Registre um productor ou mais
- Registre um customer
- Faça uma requisição POST na rota `reclamation/create/` autenticado como customer para criar uma reclamação, com o corpo da seguinte forma:
```
{
      "author": "customerName",
      "description": "descrição da reclamação",
      "emailProductor": email do produtor criado
 }
```

Retornará status code `200` se a reclamação foi realizada com sucesso

- Tente registrar uma nova reclamação contra o mesmo productor com o mesmo customer autenticado
- A requisição irá retornar um status code `400` e com responde.data:
```
{
"emailProductor":
      ["Consumidor já possui reclamação com este produtor."]
}
```
Indicando que um customer só pode realizar uma reclamação contra o mesmo productor

#### Listar reclamação
- Registre uma reclamação
- Faça uma requisição GET na rota `reclamation/list/{email do productor codificado em base 64}` autenticado como customer para listar as reclamações do productor
- Será listado todas as reclamações contra o productor
- O response.data será vazio se não existir nenhuma reclamação contra o productor

#### Deletar uma reclamação
- Registre uma reclamação
- Faça uma requisição DELETE na rota `reclamation/delete/{email do customer codificado em base 64}/` autenticado como superUser (faça o login com as credenciais de admin: email = `admin@example.com` e password = `admin` para deletar a reclamação que o customer fez contra o productor. Adicione no corpo da requisição:
```
{
    "emailProductor": email do produtor criado
}
```
Retornará status code 200 se deletado com sucesso

2021-04-25 15:17 UTC, Joao-Moura requested changes
Meu amigo kkkkk, parabéns por quase criar um CRUD em 1 semana. Em relação ao código, gostei bastante de como foi utilizado alguns shortcuts do django, porém existem algumas coisas a se melhorar. Estarei deixando aquelas que achei (pode ser que existam mais kkkk).

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        self.register_productor()
Se vc vai usar o self.register_productor() em todos os testes coloque ele no setUp()

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        self.create_tokens()
Esse comentário aqui se inclui para todos os métodos que estiverem no `setUp()`. Eles também devem conter o assertEqual por mais que seja certeza que eles ja tenham sido testados.

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        )
Faltou o `assertEqual` dessa response aqui. Novamente, por mais que ja tenha sido testada é importante ressaltar o teste.

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +class ReclamationListAPIViewTestCase(APITestCase):
Faltam testes de falha nessa viewset de List.

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        encodedEmail = 'cHJvZHVjdG9yQHRlc3RlLmNvbQ=='
Mesmo comentário ja feito anteriormente sobre o `self.register_productor()`, e agora também sobre o encodedEmail, se vc usa ele nos dois porque ele não está jundo do `self.url_list_reclamations` padrão ?

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        self.creds = self.create_tokens(user_data=self.admin_data)
Repetindo aqui de novo kkkkkkk, faça os testes nos métodos utilizados no setUp

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        return creds
Não entendi esse `return creds`. é mais eficiente salvar o creds em um self.creds

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        }
Esse `delete_data` é repetido várias vezes, salve ele em um um self.delete_data no setUp

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/urls.py
> +router.register(r'list(:?/(?P<emailProductor>.+))?', viewsets.ReclamationListAPIView, basename='listReclamation')
Se você quer que na url `reclamation/list` seja obrigatório a passagem de um email em base64 essa url está incorreta. Talvez a utilização do `mixins,RetrieveModelMixin` seja melhor (não sei se é verdade).

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/viewsets.py
> +class ReclamationListAPIView(GenericViewSet, mixins.ListModelMixin):
Na viewset `ReclamationListAPIView` entradas com emails que não existem não estão sendo tratadas e o django rest está retornando a exceção `DoesNotExist`.

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/viewsets.py
> +class ReclamationListAPIView(GenericViewSet, mixins.ListModelMixin):
Uma forma de tratar isso seria no método `get_queryset()` realizar a validação do email passado no kwargs usando o `.exists()` e caso ele não exista dando um raise de algum error (olhe as outras viewsets, pois eu não lembro em qual viewset eu utilizei uma lógica semelhante`.

2021-04-25 15:17 UTC, Joao-Moura commented on src/hortum/reclamation/viewsets.py
> +        queryset = Reclamation.objects.filter(idProductor=Productor.objects.get(user__email=emailProductor))
Essa queryset pode ser simplificada  (não testei) para:
```python
queryset = Reclamation.objects.filter(idProductor__user__email=emailProductor)
```

2021-04-25 19:05 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        return creds
Uso esse return creds porque preciso fazer requests autenticados tanto como admin, para deletar a reclamação, tanto como customer, para criar reclamação

2021-04-25 19:12 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        }
Não da poque uso o `self.productor_data['email']`, e esse productor_data é criado depois do setUp

2021-04-25 19:44 UTC, CarlosFiuza commented on src/hortum/reclamation/viewsets.py
> +        queryset = Reclamation.objects.filter(idProductor=Productor.objects.get(user__email=emailProductor))
Ok, funcionou

2021-04-25 19:44 UTC, CarlosFiuza commented on src/hortum/reclamation/viewsets.py
> +class ReclamationListAPIView(GenericViewSet, mixins.ListModelMixin):
Ok

2021-04-25 19:44 UTC, CarlosFiuza commented on src/hortum/reclamation/urls.py
> +router.register(r'list(:?/(?P<emailProductor>.+))?', viewsets.ReclamationListAPIView, basename='listReclamation')
Não funcionou com o Retrieve

2021-04-25 19:44 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        self.creds = self.create_tokens(user_data=self.admin_data)
Ok

2021-04-25 19:45 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        encodedEmail = 'cHJvZHVjdG9yQHRlc3RlLmNvbQ=='
Ok

2021-04-25 19:45 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +class ReclamationListAPIViewTestCase(APITestCase):
Ok

2021-04-25 19:45 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        )
Ok

2021-04-25 19:45 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        self.create_tokens()
Ok

2021-04-25 19:45 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        self.register_productor()
Ok

2021-04-25 21:48 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        }
Mais o productor_data é criado no setUp ? Porque se for não tem nenhum problema colocar essa parte de código lá.

2021-04-25 21:48 UTC, Joao-Moura commented on src/hortum/reclamation/tests.py
> +        return creds
Mais em vez disso vc pode passar como argumentos os dados de quem vc quer logar e salvar no self.creds o token.

2021-04-26 15:27 UTC, CarlosFiuza commented on src/hortum/reclamation/tests.py
> +        }
Não, não é criado no setUp

2021-04-28 17:35 UTC, Joao-Moura approved these changes
Funcionando como esperado eu pelo menos não consegui encontrar nenhum erro. Parabéns.

2021-04-28 18:02 UTC, LucasBraunX approved these changes
Funcionando certinho, parabéns pelo trabalho.

2021-04-28 18:52 UTC, merged