#163 Interacoes com Email
fga-eps-mds/MDS-2020-2-G6 pull request #216
Opened 2021-05-05 17:40 UTC by brenno-silva

## Descrição
- Adicionado funcionalidade de enviar email ao usuário para confirmar o cadastro.

## Está consertando alguma issue aberta?
- #163 

## Tarefas gerais realizadas
- Adição das telas de confirmação e e recorrência
- Adição do email para envio de mensagens 
- Adição da viewset `VerifyAccountView`
- Adição da permission `IsVerified`
- Adição do campo `is_verified` para users

## Como testar
1. Utilize um [email temporário](https://temp-mail.org/pt/)
2. Registre um usuário
3. Tente fazer o login sem verificar a conta
4. Abra o email e acesse o link
5. Tente fazer o login novamente

2021-05-05 23:25 UTC, Joao-Moura requested changes
Código muito bem feito, e pra falar bem a verdade curti de mais a integração com email, parabéns. Só uma coisa que eu peço é que atualizem a branch, tem muita coisa atrasada e não tenho tanta certeza se tudo irá funcionar certo quando for pra main.

2021-05-05 23:57 UTC, brenno-silva commented
> Código muito bem feito, e pra falar bem a verdade curti de mais a integração com email, parabéns. Só uma coisa que eu peço é que atualizem a branch, tem muita coisa atrasada e não tenho tanta certeza se tudo irá funcionar certo quando for pra main.

Acabei de dar o merge com as alterações mais recentes da main.

2021-05-06 00:40 UTC, Joao-Moura requested changes
Após o merge com a main passei olhando aqui novamente o código e notei alguns pontos de melhora.

2021-05-06 00:40 UTC, Joao-Moura commented on src/hortum/productor/viewsets.py
> +		return prod
Notei essa parte de código aqui que não existe mais, por algum motivo ele veio (não sei da onde kkkkk) e acabou diminuindo o coverage além de nem ser usado (não tem um endpoint nas urls).

2021-05-06 00:40 UTC, Joao-Moura commented on src/hortum/users/viewsets.py
> +        return User.objects.get(email=email)
Aqui acredito que daria para transformar em apenas uma linha
```python
return User.objects.get(email=decode_string(self.kwargs['encoded_email']))
```

2021-05-06 00:40 UTC, Joao-Moura commented on src/hortum/users/serializer.py
> +        fields = ['username', 'email', 'phone_number', 'password', 'profile_picture', 'is_verified']
Aqui é só uma dúvida, o `is_verified` ta sendo passado aqui por causa do testes certo ?

2021-05-06 01:03 UTC, brenno-silva commented on src/hortum/users/serializer.py
> +        fields = ['username', 'email', 'phone_number', 'password', 'profile_picture', 'is_verified']
Isso

2021-05-06 01:51 UTC, Joao-Moura approved these changes
Show de mais, parabéns pelos esforços.

2021-05-06 13:34 UTC, matheuscvp approved these changes
Parabéns pela implementação da verificação por e-mail, código limpo e didático, parabéns!

2021-05-06 13:44 UTC, merged