[US05] Redefinir senha
fga-eps-mds/MDS-2020-2-G6 pull request #218
Opened 2021-05-06 04:13 UTC by CarlosFiuza

## Descrição
- Adição de rotas para redefinir senha
- Adição de form para setar nova senha
- Adição de arquivos html para páginas de redefinição de senha

## Está consertando alguma issue aberta?
- #91 

## Tarefas gerais realizadas
- Adição de rotas para redefinir senha
- Adição de forms para setar senha
- Adição de templates html para páginas e email de redefinição de senha

### Teste
- Para testar crie um novo usuário com um email real;
- Acesse a rota `localhost:8000/reset_password/`;
- Insira o email cadastrado;
- Acesse seu email e clique no link `Redefinir senha`;
- Digite nova senha;
- Tente logar com a nova senha.

2021-05-06 12:54 UTC, Joao-Moura requested changes
Parabéns pelo pr, funcionalidade muito interessante. Vou estar deixando agora uns comentários aqui que eu acho interessantes serem alterados. Além deles esses dois aqui que eu não consegui marcar kkkkk:
1. Existe um arquivo `templates/hortum/email_template_name.htm`, isso ta certo mesmo ? A extensão não era pra ser html ?
2. A segunda é em relação ao título do email enviado, não daria para usar essa [ideia aqui](https://github.com/fga-eps-mds/2020.2-Hortum/blob/c4559378b69308d7f062b9461ead01ddd86a4540/src/hortum/users/models.py#L22-L31) ?

2021-05-06 12:54 UTC, Joao-Moura commented on src/hortum/templates/hortum/password_reset_confirm.html
> +        <p>Sua senha não pode ser totalmente numérica.</p>
Por mim tirava essas 3 linhas pois elas não são verificadas, então fica meio estranho ver isso daqui

2021-05-06 12:54 UTC, Joao-Moura commented on src/hortum/users/forms.py
> +            if password1 != password2:
Não da pra juntar esses dois ifs com um or ?

2021-05-06 12:54 UTC, Joao-Moura commented on src/hortum/templates/hortum/password_reset.html
> +		<input type="Submit" name="Send email">
Essa linha aqui é onde vc bota o email e o botão correto ? acredito que daria pra melhorar o html disso daqui

2021-05-07 12:54 UTC, Joao-Moura approved these changes
Funcionando perfeitamente e o código bem feito, parabéns. Acredito que vcs não conseguiram mudar o título do email, mais fazer o que kkkkkk.

2021-05-07 18:45 UTC, VitorLamego approved these changes
Testado e por aqui funcionou tudo certo !! Parabéns pelo trabalho, muito bom !!

2021-05-07 19:03 UTC, merged