#29 Padronização de documentos
fga-eps-mds/MDS-2020-2-G6 pull request #34
Opened 2021-02-19 16:34 UTC by Joao-Moura

## Descrição
- Padronização dos documentos de arquitetura e visão.

## Está concertando alguma issue aberta?
- #29 

## Tipo de mudança
 - [ ] Bugfix
 - [ ] Nova feature
 - [x] Atualização da documentação
 - [ ] Alteração de feature existente

2021-02-19 17:55 UTC, brenno-silva requested changes
Os links devem estar entre <>
Ex: Disponível em: <LINK>

2021-02-19 18:30 UTC, VitorLamego requested changes
Nos documentos referentes a Sprint eu acredito que eles possuem uma estrutura muito similar ( Planning e Review ) acredito que seja interessante diferenciar no título do documento. Por exemplo:
Sprint X - Planning
Sprint X - Review

2021-02-19 19:09 UTC, VitorLamego approved these changes

2021-02-20 22:58 UTC, brenno-silva approved these changes

2021-02-20 23:12 UTC, merged