#23 Criado Documento de Protótipo
fga-eps-mds/MDS-2020-2-G6 pull request #38
Opened 2021-02-23 16:28 UTC by VitorLamego

## Descrição
- Criação do Protótipo de Baixa Fidelidade ([Protótipo](https://www.figma.com/file/gTe5l9U0GZBIEqDAWaiyzN/MDS-Baixa-Fidelidade?node-id=0%3A1))
- Abertura do Documento de Protótipo
- Adição do Protótipo de Baixa Fidelidade ao documento

## Está concertando alguma issue aberta?
-  #23

## Tipo de mudança
 - [ ] Bugfix
 - [ ] Nova feature
 - [x] Atualização da documentação
 - [ ] Alteração de feature existente

2021-02-23 16:33 UTC, vital14 approved these changes
Ok

2021-02-23 17:29 UTC, matheuscvp approved these changes

2021-02-23 17:29 UTC, Joao-Moura requested changes
Em relação a tela favoritos eu acredito ser melhor favoritar o produtor em vez do anúncio, além disso acho que seria massa ter já um prótipo do chat. Também seria interessante ter no protótipo o que seriam os 3 botões na parte inferior do aplicativo (eu pensei em chat, tela inicial e configurações, da esquerda para a direita).

2021-02-23 19:19 UTC, CarlosFiuza approved these changes
Ótimo.

2021-02-24 16:05 UTC, brenno-silva commented
> Em relação a tela favoritos eu acredito ser melhor favoritar o produtor em vez do anúncio, além disso acho que seria massa ter já um prótipo do chat. Também seria interessante ter no protótipo o que seriam os 3 botões na parte inferior do aplicativo (eu pensei em chat, tela inicial e configurações, da esquerda para a direita).

Adicionado as telas para o Chat e Conversas, e alterado os favoritos. As abas podem ser decididas posteriormente em um protótipo de alta fidelidade.

2021-02-24 16:50 UTC, Joao-Moura approved these changes
Valeu pelo pull request.

2021-02-24 16:55 UTC, merged