#31 Politica de Contribuicao
fga-eps-mds/MDS-2020-2-G6 pull request #57
Opened 2021-03-02 21:17 UTC by VitorLamego

## Descrição
- Adição da Política de Contribuição ao projeto
- Mudança de local dos seguintes documentos: README.md, CONTRIBUTING.md e CODE_OF_CONDUCT.md para a pasta de docs

## Está concertando alguma issue aberta?
- #31 

## Tarefas gerais realizadas
Adicione aqui as tarefas realizadas
- Política de Branches
- Política de Commits
- Issues e Pull requests

2021-03-02 22:27 UTC, Joao-Moura requested changes
Os documentos ficaram muito bons, obrigado pelos esforços. Deixei alguns requests pequenos aqui. Um que eu não mencionei é sobre deixar o README no diretório principal mesmo em vez de ficar no /docs.

2021-03-02 22:27 UTC, Joao-Moura commented on docs/Politica_de_Contribuicao.md
> +`Co-Authored-by: nomeDaPessoa <emailDoGitHub>`
Aqui na linha sobre Co-autor, seria interessante colocar um exemplo para deixar bem claro para todo mundo.

2021-03-02 22:27 UTC, Joao-Moura commented on docs/CONTRIBUTING.md
> +- Utilize o [template](https://github.com/fga-eps-mds/2020.2-Hortum/blob/main/.github/pull_request_template.md) de pull request para issues
Para mim o link bugou, não sei porque.

2021-03-02 22:28 UTC, Joao-Moura commented on docs/CONTRIBUTING.md
> +- Utilize o [template](https://github.com/fga-eps-mds/2020.2-Hortum/blob/main/.github/pull_request_template.md) de pull request para issues
Acredito que seja o README no /docs

2021-03-03 18:46 UTC, VitorLamego commented on docs/CONTRIBUTING.md
> +- Utilize o [template](https://github.com/fga-eps-mds/2020.2-Hortum/blob/main/.github/pull_request_template.md) de pull request para issues
Arrumado. Em alguns repositórios vi que colocam o README.md dentro da pasta de docs também, por isso tínhamos movido

2021-03-03 19:12 UTC, Joao-Moura approved these changes

2021-03-03 19:12 UTC, merged