#58 Criando models do banco de dados e serializando
fga-eps-mds/MDS-2020-2-G6 pull request #74
Opened 2021-03-09 00:03 UTC by VitorLamego

## Descrição
- Criação das models das entidades do projeto com as suas serializações

## Está concertando alguma issue aberta?
#58 

## Tarefas gerais realizadas
- Criação da entidade de Produtores
- Criação da entidade de Compradores
- Criação da entidade de Localização
- Criação da entidade de Picture
- Criação da entidade de Anúncios

2021-03-09 00:31 UTC, Joao-Moura reviewed
Ok, agradeço muito pelos esforços e posso ve que eles deram frutos, porém iréi sugerir algumas mudanças em comentários separados.

2021-03-09 00:40 UTC, Joao-Moura requested changes
**[Se tornará uma issue pra Sprint 5]**
A primeira delas é em relação ao uso de um User model customizado.
- Acredito que usando esse [AbstractUser](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project), o projeto se torne mais tranquilo para futuras mudanças.
-  Com isso as classes que utilizando herança da users.User vão apenas sofre [uma mudança](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#extending-the-existing-user-model).
- Para utilizar essa característica é necessário ja desde a primeira migrations estar implementado, como não está o django sugere os seguintes passos para [conversão](https://code.djangoproject.com/ticket/25313#comment:9).

2021-03-09 00:43 UTC, Joao-Moura requested changes

2021-03-09 00:43 UTC, Joao-Moura commented on requirements.txt
> +Pillow==8.1.2
A segunda é em relação ao novo pacote Pillow, uma falha minha na hora de implementar o docker foi apenas realizar o pip install no Dockerfile, então como forma de arrumar esse erro sugiro:
- Editar o arquivo startup.sh da seguinte forma
```
#!/bin/sh

pip install -r requirements.txt
cd src
...
```

2021-03-09 00:52 UTC, Joao-Moura requested changes
E minha terceira request é em relação a serialização que está sendo feita no mesmo arquivo da models.py. Isso representa uma má prática de programação, visto que junta dois arquivos de funções distintas em apenas um, além de que será no arquivo serializer.py que estaremos fazendo as validações dos campos antes de mandar pro banco.
- Separem os serializers das models em um arquivo chamado serializer.py para **cada app** que possuir uma model que precise de serialização.
- Sugiro que olhem a documentação do django-rest sobre [serialização](https://www.django-rest-framework.org/tutorial/1-serialization/#using-modelserializers) utilizando o modelSerializer em vez do Serializer.
- Com essa alteração, o arquivo src/hortum/json.py poderá ser apagado, já que o DRF será capaz de realizar tanto a serialização como a deserialização automáticamente.

2021-03-09 13:39 UTC, VitorLamego commented on requirements.txt
> +Pillow==8.1.2
Como estamos utilizando o docker, para que seja instalado as novas dependências basta utilizar o comando: sudo docker-compose up --build, o que resolve o problema descrito acima.

2021-03-11 01:49 UTC, Joao-Moura approved these changes
Aceitando os dois requests que foram refatorados e estendendo o segundo request para uma nova issue da Sprint

2021-03-11 01:53 UTC, matheuscvp approved these changes

2021-03-11 01:54 UTC, merged